version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/rpcsx-ui-kit"
    schedule:
      interval: "weekly"
    groups:
      deps:
        patterns: 
          - "*"
  - package-ecosystem: "npm"
    directory: "/electron"
    schedule:
      interval: "weekly"
    groups:
      deps:
        patterns: 
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      deps:
        patterns: 
          - "*"
