version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      deps:
        patterns: 
          - "*"
  - package-ecosystem: "cargo"
    directory: "/src-tauri" 
    schedule:
      interval: "weekly"
    groups:
      deps:
        patterns: 
          - "*"