"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "/rpcsx-ui/src/**/locales/en.json",
    "translation": "%original_path%/%locale%.json"
  }
]
